remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
title: [Bavo D.C. Campo]
description: [Hi there! Welcome to my page.]
show_downloads: true
exclude: [Manual.txt, cv.md]
